// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type LoginInput struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,gte=8"`
}

type LoginResponse struct {
	Success bool    `json:"success"`
	Message string  `json:"message"`
	Token   *string `json:"token,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Name     string       `json:"name" validate:"required,min=3"`
	Role     RegisterRole `json:"role" validate:"required"`
	Email    string       `json:"email" validate:"required,email"`
	Password string       `json:"password" validate:"required,gte=8"`
}

type RegisterResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type RegisterRole string

const (
	RegisterRoleEventOrganizer RegisterRole = "EventOrganizer"
	RegisterRoleUser           RegisterRole = "User"
)

var AllRegisterRole = []RegisterRole{
	RegisterRoleEventOrganizer,
	RegisterRoleUser,
}

func (e RegisterRole) IsValid() bool {
	switch e {
	case RegisterRoleEventOrganizer, RegisterRoleUser:
		return true
	}
	return false
}

func (e RegisterRole) String() string {
	return string(e)
}

func (e *RegisterRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RegisterRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RegisterRole", str)
	}
	return nil
}

func (e RegisterRole) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RegisterRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RegisterRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
