// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateTicketCategoryInput struct {
	Name string `json:"name" validate:"required,gte=3"`
}

type CreateTicketCategoryResponse struct {
	Status  bool   `json:"status"`
	Message string `json:"message"`
}

type CreateTicketInput struct {
	CategoryID     int                   `json:"category_id" validate:"required,gte=0"`
	TicketDetail   *TicketDetailInput    `json:"ticket_detail" validate:"required"`
	TicketVariants []*TicketVariantInput `json:"ticket_variants" validate:"required,dive"`
}

type CreateTicketResponse struct {
	Status  bool   `json:"status"`
	Message string `json:"message"`
}

type DeleteTicketCategoryResponse struct {
	Status  bool   `json:"status"`
	Message string `json:"message"`
}

type DeleteTicketResponse struct {
	Status  bool   `json:"status"`
	Message string `json:"message"`
}

type LoginInput struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,gte=8"`
}

type LoginResponse struct {
	Success bool    `json:"success"`
	Message string  `json:"message"`
	Token   *string `json:"token,omitempty"`
}

type MeResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	User    *User  `json:"user,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Name     string       `json:"name" validate:"required,min=3"`
	Role     RegisterRole `json:"role" validate:"required"`
	Email    string       `json:"email" validate:"required,email"`
	Password string       `json:"password" validate:"required,gte=8"`
}

type RegisterResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Ticket struct {
	ID             int              `json:"id"`
	CategoryTicket *TicketCategory  `json:"category_ticket"`
	Organizer      *User            `json:"organizer"`
	TicketDetail   *TicketDetail    `json:"ticket_detail"`
	TicketVariants []*TicketVariant `json:"ticket_variants"`
}

type TicketCategory struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type TicketDetail struct {
	ID               int    `json:"id"`
	Title            string `json:"title"`
	Slug             string `json:"slug"`
	Description      string `json:"description"`
	Location         string `json:"location"`
	EventDate        string `json:"event_date"`
	EventStartTime   string `json:"event_start_time"`
	EventEndTime     string `json:"event_end_time"`
	TermAndCondition string `json:"term_and_condition"`
}

type TicketDetailInput struct {
	Title            string   `json:"title" validate:"required,gte=8"`
	Description      string   `json:"description" validate:"required,gte=10"`
	Location         string   `json:"location" validate:"required,gte=3"`
	LineUps          []string `json:"line_ups" validate:"required,dive,required,gt=0"`
	EventDate        string   `json:"event_date" validate:"required"`
	EventStartTime   string   `json:"event_start_time" validate:"required"`
	EventEndTime     string   `json:"event_end_time" validate:"required"`
	TermAndCondition string   `json:"term_and_condition" validate:"required"`
}

type TicketVariant struct {
	ID     int      `json:"id"`
	Name   string   `json:"name"`
	Price  int      `json:"price"`
	Perks  []string `json:"perks"`
	Quota  int      `json:"quota"`
	Active bool     `json:"active"`
}

type TicketVariantInput struct {
	Name   string   `json:"name" validate:"required,gte=3"`
	Price  int      `json:"price" validate:"required,gte=0"`
	Perks  []string `json:"perks" validate:"required"`
	Quota  int      `json:"quota" validate:"required,gte=0"`
	Active bool     `json:"active"`
}

type UpdateTicketCategoryInput struct {
	Name string `json:"name" validate:"required,gte=3"`
}

type UpdateTicketCategoryResponse struct {
	Status  bool   `json:"status"`
	Message string `json:"message"`
}

type UpdateTicketInput struct {
	CategoryID     int                         `json:"category_id" validate:"required,gte=0"`
	TicketDetail   *TicketDetailInput          `json:"ticket_detail" validate:"required,dive,required"`
	TicketVariants []*UpdateTicketVariantInput `json:"ticket_variants" validate:"required,dive,required"`
}

type UpdateTicketResponse struct {
	Status  bool   `json:"status"`
	Message string `json:"message"`
}

type UpdateTicketVariantInput struct {
	ID     *int     `json:"id,omitempty" validate:"omitempty,gt=0"`
	Name   string   `json:"name" validate:"required,gte=3"`
	Price  int      `json:"price" validate:"required,gte=0"`
	Perks  []string `json:"perks" validate:"required"`
	Quota  int      `json:"quota" validate:"required,gte=0"`
	Active bool     `json:"active"`
}

type User struct {
	ID    int    `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Role  string `json:"role"`
}

type AuthRole string

const (
	AuthRoleAll            AuthRole = "All"
	AuthRoleSuperAdmin     AuthRole = "SuperAdmin"
	AuthRoleEventOrganizer AuthRole = "EventOrganizer"
	AuthRoleUser           AuthRole = "User"
)

var AllAuthRole = []AuthRole{
	AuthRoleAll,
	AuthRoleSuperAdmin,
	AuthRoleEventOrganizer,
	AuthRoleUser,
}

func (e AuthRole) IsValid() bool {
	switch e {
	case AuthRoleAll, AuthRoleSuperAdmin, AuthRoleEventOrganizer, AuthRoleUser:
		return true
	}
	return false
}

func (e AuthRole) String() string {
	return string(e)
}

func (e *AuthRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthRole", str)
	}
	return nil
}

func (e AuthRole) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuthRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuthRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RegisterRole string

const (
	RegisterRoleEventOrganizer RegisterRole = "EventOrganizer"
	RegisterRoleUser           RegisterRole = "User"
)

var AllRegisterRole = []RegisterRole{
	RegisterRoleEventOrganizer,
	RegisterRoleUser,
}

func (e RegisterRole) IsValid() bool {
	switch e {
	case RegisterRoleEventOrganizer, RegisterRoleUser:
		return true
	}
	return false
}

func (e RegisterRole) String() string {
	return string(e)
}

func (e *RegisterRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RegisterRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RegisterRole", str)
	}
	return nil
}

func (e RegisterRole) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RegisterRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RegisterRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
