type Mutation {
  login(input: LoginInput!): LoginResponse
  register(input: RegisterInput!): RegisterResponse

  createTicket(input: CreateTicketInput!): CreateTicketResponse @auth(role:[EventOrganizer])
  updateTicket(input: UpdateTicketInput!, ticket_id: Int!): UpdateTicketResponse @auth(role:[EventOrganizer])
  deleteTicket(ticket_id: Int!): DeleteTicketResponse @auth(role:[EventOrganizer])

  createTicketCategory(input: CreateTicketCategoryInput!): CreateTicketCategoryResponse @auth(role:[SuperAdmin])
  updateTicketCategory(input: UpdateTicketCategoryInput!, ticket_category_id: Int!): UpdateTicketCategoryResponse @auth(role:[SuperAdmin])
  deleteTicketCategory(ticket_category_id: Int!): DeleteTicketCategoryResponse @auth(role:[SuperAdmin])
}

