type TicketCategory {
  id: Int!
  name: String!
}

type TicketDetail {
  id: Int!
  title: String!
  slug: String!
  description: String!
  location: String!
  event_date: String!
  event_start_time: String!
  event_end_time: String!
  term_and_condition: String!
}

type TicketVariant {
  id: Int!
  name: String!
  price: Int!
  perks: [String!]!
  quota: Int!
  active: Boolean!
}

type Ticket {
  id: Int!
  category_ticket: TicketCategory!
  organizer: User!
  ticket_detail: TicketDetail!
  ticket_variants: [TicketVariant!]!
}

type CreateTicketResponse {
  status: Boolean!
  message: String!
}

input TicketDetailInput {
  title: String! @goTag(key:"validate",value:"required,gte=8")
  description: String! @goTag(key:"validate",value:"required,gte=10")
  location: String! @goTag(key:"validate",value:"required,gte=3")
  line_ups: [String!]! @goTag(key:"validate" , value:"required,dive,required,gt=0")
  event_date: String! @goTag(key:"validate",value:"required")
  event_start_time: String! @goTag(key:"validate",value:"required")
  event_end_time: String! @goTag(key:"validate",value:"required")
  term_and_condition: String! @goTag(key:"validate",value:"required")
}

input TicketVariantInput {
  name: String! @goTag(key:"validate",value:"required,gte=3")
  price: Int! @goTag(key:"validate",value:"required,gte=0")
  perks: [String!]! @goTag(key:"validate",value:"required")
  quota: Int! @goTag(key:"validate",value:"required,gte=0")
  active: Boolean!
}

input UpdateTicketVariantInput {
  id: Int @goTag(key:"validate",value:"omitempty,gt=0")
  name: String! @goTag(key:"validate",value:"required,gte=3")
  price: Int! @goTag(key:"validate",value:"required,gte=0")
  perks: [String!]! @goTag(key:"validate",value:"required")
  quota: Int! @goTag(key:"validate",value:"required,gte=0")
  active: Boolean!
}

input CreateTicketInput {
  category_id: Int! @goTag(key:"validate",value:"required,gte=0")
  ticket_detail: TicketDetailInput! @goTag(key:"validate",value:"required")
  ticket_variants: [TicketVariantInput!]! @goTag(key:"validate",value:"required,dive")
}

type UpdateTicketResponse {
  status: Boolean!
  message: String!
}

input UpdateTicketInput {
  category_id: Int! @goTag(key:"validate",value:"required,gte=0")
  ticket_detail: TicketDetailInput! @goTag(key:"validate",value:"required,dive,required")
  ticket_variants: [UpdateTicketVariantInput!]! @goTag(key:"validate",value:"required,dive,required")
}

type DeleteTicketResponse {
  status: Boolean!
  message: String!
}

input CreateTicketCategoryInput {
  name: String! @goTag(key:"validate", value:"required,gte=3")
}

type CreateTicketCategoryResponse {
  status: Boolean!
  message: String!
}

input UpdateTicketCategoryInput {
  name: String! @goTag(key:"validate", value:"required,gte=3")
}

type UpdateTicketCategoryResponse {
  status: Boolean!
  message: String!
}

type DeleteTicketCategoryResponse {
  status: Boolean!
  message: String!
}

