# GraphQL schema example
#
# https://gqlgen.com/getting-started/

directive @goTag(
  key: String!
  value: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION


input LoginInput {
  email: String! @goTag(key:"validate",value:"required,email")
  password: String! @goTag(key:"validate", value:"required,gte=8")
}

enum RegisterRole {
  EventOrganizer
  User
}

input RegisterInput {
  name: String! @goTag(key:"validate", value:"required,min=3")
  role: RegisterRole! @goTag(key:"validate", value:"required")
  email: String! @goTag(key:"validate",value:"required,email")
  password: String! @goTag(key:"validate", value:"required,gte=8")
}

type LoginResponse {
  success: Boolean!
  message: String!
  token: String
}

type RegisterResponse {
  success: Boolean!
  message: String!
}

type Mutation {
  login(input: LoginInput): LoginResponse
  register(input: RegisterInput): RegisterResponse
}

